# Jenkins location and login
jenkins:  http://localhost:8080
username: None  # optional
password: None  # optional

# Repository urls
repo: file:///tmp/repo/
branches:
  - file:///tmp/repo/branches/
  - file:///tmp/repo/experimental/
  - file:///tmp/repo/releases/

# Repository login
scm-username: None  # optional
scm-password: None  # optional

# Job to use as a template for new jobs
template: new-job-template

# Character with which to replace '/' in branch names
namesep: '-'

# Template string for new job names
# The following placeholders are available:
# Given a branch file:///tmp/repo/branches/feature-one
#   {branch} -> expands to the name of the branch (feature-one)
#   {path}   -> expands to the full path to the branch, relative to
#               the repository root (branches/feature-one)
#   {n}      -> nth backreference of the branch regex
namefmt: '{branch}'

# If false, a job will never be overwritten if it exists
# If true, a job will be overwritten if the new configration
# differs from the old one.
overwrite: true

# State of newly created or overwritten jobs. One of:
#   true       -> jobs will be enabled
#   false      -> jobs will be disabled
#   'template' -> jobs will inherit the state of their template job
#   'sticky'   -> new jobs inherit the state of the template job -
#                 overwritten jobs keep their previous state.
enable: 'sticky'

# Literal substitute of strings in template job
# Useful for certain plugins (eg. sidebar links)
substitute:
  '@@JOB_NAME@@' : '{branch}'

# List of branches to ignore (regular expressions)
ignore:
  - 'branches/.*-nobuild'
  - 'experimental/john/.*'

# Maps branch names (regular expressions) to config dictionaries that
# may overwrite any of the previously specified options. Defaults to
# "refs: '.*'".
refs:
  - 'branches/(.*)'
  - 'releases/(.*)':
      'template': 'release-template'
      'namefmt':  'release-{short}'
      'enable':   false
